### ISSUE TITLE
onLoad()无法获取页面参数

### ISSUE THREAD

**Issue by wangjikill** [wxajs/wxa#3]
官方手册：
> 生命周期回调函数
生命周期的触发以及页面的路由方式详见
onLoad(Object query)
页面加载时触发。一个页面只会调用一次，可以在 onLoad 的参数中获取打开当前页面路径中的参数。

**Comment by Genuifx** [comment]
贴一下详细用法把，目前不管是`mixin`还是页面实例都是可以拿到对应的 query 的

**Comment by wangjikill** [comment]
<script>
import { Page} from "@wxa/core";

@Page
export default class Test {
  onLoad(setting) {
    console.log(setting)
   //结果是{}
  }
}
</script>

<config>
{
    "navigationBarTitleText": "测试"
}
</config>

<template>
</template>

<style lang="scss">
</style>

**Comment by Genuifx** [comment]
@wangjikill 这样子是取得query的，检查下跳转过来参数哦

如果是直接从开发者工具进入页面的话要设置跳转参数：

![image](https://user-images.githubusercontent.com/10156994/58067267-4948f980-7bbf-11e9-9e36-54bf8417c64e.png)

如果是其他页面跳转的话可以参考这种用法：

```js
this.$router.push('path/to/you/page?a=1&b=2')
```

**Comment by wangjikill** [comment]
谢谢，我对文档理解错了。
