### ISSUE TITLE
【enhance】css模块分离

### ISSUE THREAD

**Issue by biaodoit** [wxajs/wxa#8]
`@import "./test.scss";`

app.scss中通过以上代码引入css时，test.scss更新无法触发css重新编译

**Comment by wangjikill** [comment]
确实是，需要退出后，重新编译。watch模式下不能触发编译

**Comment by Genuifx** [comment]
是的，scss文件的依赖由于经过一次 `node-sass ` 编译之后在wxa编译阶段就拿不到相关依赖信息了，后续做一个优化。 PR welcome

**Comment by Genuifx** [comment]
升级cli到2.1.5 升级项目中的compiler-sass到2.1 即可修复
